concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker"
  url = "http://158.160.87.198:80"
  id = 1
  token = "Bh_84swssVKpBjs5EkzA"
  token_obtained_at = 2024-03-18T03:48:13Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://158.160.87.198:80"
  [runners.docker]
    tls_verify = false
    image = "158.160.87.198:4431/images/astra-orel:v4"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    network_mode = "gitlab-network"
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "docker-runner"
  url = "http://158.160.87.198:80"
  id = 5
  token = "u4sbnPX1rRQsQx44-zcz"
  token_obtained_at = 2024-04-05T05:45:57Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  clone_url = "http://158.160.87.198:80"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "158.160.87.198:4431/example-gitlab/gcc-13.02:v1"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/cache"]
    network_mode = "gitlab-network"
    shm_size = 0
    network_mtu = 0
